language: python
sudo: false
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
  #- "pypy3.5"  fails due to timing tests

install:
  - pip install tox
  - pip install codecov

script:
  - tox -e py${TRAVIS_PYTHON_VERSION:0:1}${TRAVIS_PYTHON_VERSION:2:1}
  - tox -e coverage -- xml
  - codecov --file=coverage.xml

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    python: "3.6"
