dist: trusty
sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -e .
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install pytest-travis-fold
  - pip install codecov
script:
  - py.test
after_success:
 - codecov
