dist: trusty
sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install nose
- pip install coverage
- pip install codacy-coverage
script:
- nosetests --with-coverage --cover-xml --cover-package=lproc
after_success:
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: nlgranger
  password:
    secure: dvowuAKe4h69ovwDKMOux6pidceORyQ37rYvFD7oCe4kKP7R5l2JL7Mdxb4anJciUPyqox782xC1l13hMN6IGElGWotFuo29LJfQsAtJa+3Jb+TdiLSdzAnNp+peVAhA180v6kED9I/clnG9vxJsqbxWumcCIsCCgYTbyoFD/5qxZbablmWmQ/QI+D22FOpqWNJwq95cBCKZNxR+zJTYsl+CWJgdnzs38iOyFyLQl2NZGvrqlVjtyAgaUmg3C9YU9Z9T+nx2/QG7R11vpe2qteB3KwXmtpchKWZJd9WnjtKE6PPhUzl7mMjBjkW4DaHwt4pih1DG79lLEFrN7bEPHH4nthA8OUyCKPsDe4em15S9caZfFmHg6B2NqSMzGL73JSktlK68bXJApdKdJq1VmZgsDk/5preDHtDm7HJK3vwbE1iFpdTeTSD/dSg2XlcLXN6R/CwuVTSri67i3064H8BEL00riKf5PTTWmUMXsNlRDR1WtDokMurAgThK0Pzgda5wEYlp0oWwv0vIf0tZhdjKM3xm5KvOVEl/WjWJVx6yDB+B70JLwFUc0/VC2i9FEJxDNhoRToIcyJoFxoGnY66vBjlCXgMDO9g1V2hr3qoLCLEw5MkI+XkSBvvfZoEF7/sdAiPs3kgjBGBXypb4gHLNLrCFow7Cy1GgOg7YwZ0=
  on:
    tags: true
