language: python
cache: pip
python:
  - '3.6'
install:
  - pip install -e .
  - pip install numpy
  - pip install nose
  - pip install coverage
  - pip install codacy-coverage
  - pip install sphinx
script:
  - nosetests --with-coverage --cover-xml --cover-package=lproc
  - python -m sphinx -M doctest docs docs/_build
after_success:
  - python-codacy-coverage -r coverage.xml
