dist: trusty
sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install nose
- pip install coverage
- pip install pytest-cov
- pip install pytest-travis-fold
- pip install codecov
script:
- nosetests
after_success:
- codecov
deploy:
  provider: pypi
  user: nlgranger
  password:
    secure: lGkZTLQX8oYwYuQMJ1KcqIvypyoF30V2mkNYs2tZMLd/XMKb7CajW2uJvs9F7RAD69PARb4UWwTbm1zGs7cp5PRqomCktI4G9n6JYvygaK4Jh1V4GIUbOJ9U5BrIqxUMfOByrLlZ2XqanNLbu7z28o2bisgdVu1R4ijWqHeUM06Guz2ff4tVoCoxS2gQSIuptd7nb5tJbztdHsY8xCTYB1DHbz4JnlZyxI0r40g3ZV/HpGVdmmpCzeMSbs5Z3/l43HhtjLyiq01pTht8My0zPwmQxF98G7LNEKF/azwy0ijMZwF5IQOlNEqlsm6r3vqdtiwkfREfA4jtkmA3Nx3/RE65Uk3ozqH91sZTZmyueHFMAUA3+xCxOG5HtgWUfadbv/Xtv6vQUvqCXM10FGHwSq0uK2Ad8FgoLoddfHB0Bcn7hlkJCsUeXQ0MH/rJbXESfbxgEL89treeIAEh5kfRxLAevcXI1XYBNIpX7TwynXTdQCmNKADqzYJYa+H7YqlKY4j05PbUZrXARjOGBuJStRX8thFvdOIXkzffWCnQ1b3F7s2BihaJd0ka2/8uxursmq3QCsIkv0HZ29yalLRZrZ0QgNn8C8ituE6dWuqf/ltMx1pWZN1hf6itj0Zkvl2B6E1g1Z6vTl84992xWjhNuHQgE0eDllv+32my12kG5kk=
  on:
    tags: true